import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Layout from "./components/Layout";
import ModalProvider from "@/provider/ModalProvider";
import { Toaster } from "react-hot-toast";
import { ProviderRedux } from "@/provider/ReduxProvider";
import SessionProviderNext from "@/provider/SessionProviderNext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProviderRedux>
          <SessionProviderNext>
            <Toaster />
            <ModalProvider />
            <Layout>{children}</Layout>
          </SessionProviderNext>
        </ProviderRedux>
      </body>
    </html>
  );
}
